### ISSUE TITLE
Fix locked dependencies of certain modules from making the recipe unresolvable

### ISSUE THREAD

**Issue by NightJar** [silverstripe/cwp-installer#18]
At current bugs from our release tool that were present at the time of the `2.0.0-rc1` release (and since fixed) are affecting the resolvablity of `2.0.0-rc2`.

We need to compile a list of affected modules, and make adjustments to their requirements, and/or minor releases to encompass identified regressions also.

Ultimately this will likely culminate in an `rc3`.

---

## Future reference

- [x] https://github.com/silverstripe/silverstripe-content-widget/blob/2.0.0/composer.json#L14
- [ ] https://travis-ci.org/silverstripe/recipe-content-blocks/jobs/361905412#L527
- [ ] https://travis-ci.org/silverstripe/cwp-recipe-search/jobs/361904643#L526
- [ ] https://travis-ci.org/silverstripe/recipe-reporting-tools/jobs/361904531#L525

### ~TODO~
 - ~check all other modules that didn't have a version bump between `2.0.0-rc1` and `2.0.0-rc2`to ensure they don't have locked version constraints like `silverstripe/content-widget` and `cwp/cwp-search`~

#### Affected modules:
 - silverstripe/externallinks
 - silverstripe/sitewidecontent-report
 - silverstripe/askismet

**Comment by robbieaverill** [comment]
* silverstripe/content-widget https://github.com/silverstripe/silverstripe-content-widget/blob/2.0.1/composer.json (retagged)
* silverstripe/elemental-blocks https://github.com/silverstripe/silverstripe-elemental-blocks/blob/1.0.0-rc2/composer.json (retagged)
* cwp/cwp-search https://github.com/silverstripe/cwp-search/blob/1.0.0-rc2/composer.json (retagged)
* silverstripe/externallinks can be re-tagged as 2.0.1 once https://github.com/silverstripe/silverstripe-externallinks/pull/48 is merged

I've re-run the master branches for these recipes:

* https://travis-ci.org/silverstripe/recipe-reporting-tools/builds/344613465
* https://travis-ci.org/silverstripe/recipe-content-blocks/builds/344607810
* https://travis-ci.org/silverstripe/cwp-recipe-search/builds/340672544

**Comment by NightJar** [comment]
Re-releasing the recipes should see them fixed. Thanks to @robbieaverill other messes have been sorted out, and the remaining three modules can be re-tagged (new versions) now they've also been patched up, such as externallinks as mentioned above, or were only affected by a constraint in the last tagged version only (release tool bug since fixed).

**Comment by NightJar** [comment]
Fixed with release [2.0.0-rc3](https://github.com/silverstripe/cwp-installer/releases/tag/2.0.0-rc3)
